import { Router } from "express";
import { roleAuth } from "../../common/middleware/role-auth.middleware";
import * as controller from "./community.controller";

const router = Router();
router.use(roleAuth(["ADMIN", "USER"]));
router.get("/admin/reports", roleAuth(["ADMIN"]), controller.adminReports);
router.patch("/admin/reports/:id", roleAuth(["ADMIN"]), controller.reviewReport);
router.get("/admin/listings", roleAuth(["ADMIN"]), controller.adminListings);
router.get("/admin/activity", roleAuth(["ADMIN"]), controller.adminActivity);
router.get("/admin/stats", roleAuth(["ADMIN"]), controller.adminStats);
router.get("/blocked-users", controller.blockedUsers);
router.get("/listings", controller.list);
router.get("/my-listings", controller.mine);
router.get("/listings/:id", controller.one);
router.post("/listings", controller.create);
router.patch("/listings/:id", controller.update);
router.delete("/listings/:id", controller.remove);
router.patch("/listings/:id/status", controller.status);
router.post("/listings/:id/report", controller.report);
router.post("/listings/:id/like", controller.like);
router.delete("/listings/:id/like", controller.unlike);
router.get("/users/:userId/profile", controller.userProfile);
router.post("/users/:userId/follow", controller.follow);
router.delete("/users/:userId/follow", controller.unfollow);
router.post("/users/:userId/block", controller.block);
router.delete("/users/:userId/block", controller.unblock);
router.post("/conversations", controller.startChat);
router.get("/conversations", controller.conversations);
router.get("/conversations/:id/messages", controller.messages);
router.post("/conversations/:id/messages", controller.send);
router.patch("/offers/:messageId", controller.offer);
router.post("/ai-advice", controller.aiAdvice);
export default router;
